### ISSUE TITLE
Similar Lib for Writeable Streams?

### ISSUE THREAD

**Issue by adampatarino** [calvinmetcalf/noms#1]
Maybe this is a weird question, but noms helped me write a read stream from an SFTP server and I'm wondering if there's something similar for write streams? Specifically being able to have a "before" function to setup the connection to the SFTP before beginning to read the file was very helpful, I'm looking for that same idea for writeable streams. 

I can't seem to discern how you built out the `before` function from reading the noms source code.

**Comment by calvinmetcalf** [comment]
with a writable stream you can usually just do something like 

```
var first = true;
... then inside stream

if (first) {
  // do first things
  first = false;
}
```

**Comment by adampatarino** [comment]
@calvinmetcalf ok, yeah I think I was just over thinking it. I figured it out with your advice and using [flush-write-stream](https://www.npmjs.com/package/flush-write-stream) to close the connection cleanly after the writing was done.

Thanks!
