### ISSUE TITLE
Listening for unpipe Event

### ISSUE THREAD

**Issue by adampatarino** [calvinmetcalf/noms#2]
Is there anyway to listen for an unpipe event called on a readstream so I can run a callback? For example, I'm opening an SFTP connection using the `before` hook in noms and the readstream starts reading file, after some data comes across, I close the readstream with `unpipe`. I still need to close the SFTP otherwise the connection eventually times out.

Is there an `after` method similar to the `before` method that noms uses that can be used inside the readstream definition?

**Comment by calvinmetcalf** [comment]
You can just listen for the unpipe event event yourself

**Comment by adampatarino** [comment]
Well that's my point. If I do something like: 

```javascript
function createStream() {
    /**
      * Define read() and before()
      */

    let readStream = noms(read,before);

    readStream.on('unpipe', function(){
        console.log('unpiped');
    });

    return readStream;
}
```

I never hear from the unpipe event hook.The [docs I've found](https://nodejs.org/api/stream.html#stream_event_unpipe) on the unpipe event are strictly for use on the write stream, so I'm not sure readStreams even listen for it.

Listening for the unpipe event outside of the `createStream` constructor isn't helpful, because I won't have access to the SFTP instance that's instantiated in the `before()` function.

Thanks for your help. I appreciate you taking the time to walk through this with me.

**Comment by calvinmetcalf** [comment]
why don't you set the listener for unpipe on the SFTP in the before function?

**Comment by adampatarino** [comment]
Turns out I just needed to emit the event on the stream instance. With the above code, this illustrates how I fixed my problem:

```javascript
let stream = createStream();

// explicitly call an unpipe event on the read stream so it gets caught
stream.emit('unpipe');
```

ReadStreams don't normally get the unpipe event passed to them when you call `stream.unpipe(write)`, the writeStream does. But explicitly emitting an event worked.

Thanks again for your help :)
